export const blogList = [
  {
    id: 1,
    title: '7 CSS tools you should be using ',
    category: 'development',
    subCategory: ['frontend', 'ui/ux', 'design'],
    url:"https://raw.githubusercontent.com/CodeNinjaUsman/React-markdown-Blog/main/README.md",
    authorName: 'John Doe',
    authorAvatar: '/assets/images/author.jpg',
    createdAt: 'June 03, 2021',
    cover: 'https://raw.githubusercontent.com/peterthehan/peterthehan/master/assets/twitter.svg',
  },
  {
    id: 2,
    title: 'Milan Places That Highlight The City',
    category: 'travel',
    subCategory: ['vacation', 'holidays', 'sight seeing'],
    url:"https://raw.githubusercontent.com/CodeNinjaUsman/ChatingSpace/main/studuybud-real/StudyBud/README.md",
    authorName: 'John Doe',
    authorAvatar: '/assets/images/author.jpg',
    createdAt: 'June 03, 2021',
    cover: '/assets/images/f67396fc3cfce63a28e07ebb35d974ac.jpg',
  },
  {
    id: 3,
    title: 'Online Shopping – An Alternative to Shopping in the Mall',
    category: 'shopping',
    subCategory: ['e-commerce store', 'clothing', 'shopping store'],
    url:
      "https://raw.githubusercontent.com/CodeNinjaUsman/ChatingSpace/main/studuybud-real/StudyBud/README.md",
    authorName: 'John Doe',
    authorAvatar: '/assets/images/author.jpg',
    createdAt: 'June 03, 2021',
    cover: '/assets/images/fQwuyKJ9qxjSbr6REcgtmW-1200-80.jpg',
  },
  {
    id: 4,
    title: 'ADVENTURE IN YOU',
    category: 'adventure',
    subCategory: ['adrenaline', 'stay-fit', 'lifestyle'],
    url:
      "https://raw.githubusercontent.com/CodeNinjaUsman/ChatingSpace/main/studuybud-real/StudyBud/README.md",
    authorName: 'John Doe',
    authorAvatar: '/assets/images/author.jpg',
    createdAt: 'June 03, 2021',
    cover: '/assets/images/graphic-design-trends.png',
  },
  {
    id: 5,
    title: 'Loaded BBQ Baked Potatoes',
    category: 'cooking',
    subCategory: ['bbq', 'food', 'lifestyle'],
    url:
      "https://raw.githubusercontent.com/CodeNinjaUsman/ChatingSpace/main/studuybud-real/StudyBud/README.md",
    authorName: 'John Doe',
    authorAvatar: '/assets/images/author.jpg',
    createdAt: 'June 03, 2021',
    cover: '/assets/images/make-it-personal.jpg',
  },
  {
    id: 6,
    title: 'Beyond the Beach',
    category: 'travel',
    subCategory: ['beaches', 'sea', 'holidays'],
    url:
      "https://raw.githubusercontent.com/CodeNinjaUsman/ChatingSpace/main/studuybud-real/StudyBud/README.md",
    authorName: 'John Doe',
    authorAvatar: '/assets/images/author.jpg',
    createdAt: 'June 03, 2021',
    cover:
      '/assets/images/Purple-Combination-colors-graphic-design-predictions-1024x576-1024x576.jpg',
  },
  {
    id: 7,
    title: 'Art & Perception',
    category: 'art',
    subCategory: ['skill', 'design', 'passion'],
    url:
      "https://raw.githubusercontent.com/CodeNinjaUsman/ChatingSpace/main/studuybud-real/StudyBud/README.md",
    authorName: 'John Doe',
    authorAvatar: '/assets/images/author.jpg',
    createdAt: 'June 03, 2021',
    cover: '/assets/images/Synthwave-Postmodern.jpg',
  },
];
